baseURL = 'https://collapsar.aguad.dev'
languageCode = 'en-us'
title = 'Collapsar'
description = "test"

[params.docs]
descriptions = true
backToTop = true
themeColor = "cardinal"
darkMode = true
sidebarIcons = true
titleIcon = true
prism = true
prismTheme = "twilight"

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup.goldmark.renderer]
    unsafe = true

[[menu.primary]]
    name  = "Docs"
    url = "/docs/"
    identifier = "docs"
    weight = 10